name: Generate Clash subscription
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install deps
        run: pip install requests pyyaml
      - name: Run script
        run: python fetch_and_generate.py
      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add docs/clash.yaml
          git commit -m "update subscription" || echo "No changes"
          git push
